AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Tweeter Milestone 3

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 256
    Tracing: Active
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"
      
Resources:
  GetFollowerCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetFollowerCountHandler.handler
      Events:
        GetFollowerCountApi:
          Type: Api
          Properties:
            Path: /follower/count
            Method: post

  GetFolloweeCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetFolloweeCountHandler.handler
      Events:
        GetFolloweeCountApi:
          Type: Api
          Properties:
            Path: /followee/count
            Method: post
