AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Tweeter Milestone 3

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x
    MemorySize: 256
    Tracing: Active
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"
      
Resources:
  GetFollowerCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetFollowerCountHandler.handler
      Events:
        GetFollowerCountApi:
          Type: Api
          Properties:
            Path: /follower/count
            Method: post

  GetFolloweeCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetFolloweeCountHandler.handler
      Events:
        GetFolloweeCountApi:
          Type: Api
          Properties:
            Path: /followee/count
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: LoginHandler.handler
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /login
            Method: post

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: RegisterHandler.handler
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /register
            Method: post

  FollowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: FollowHandler.handler
      Events:
        FollowApi:
          Type: Api
          Properties:
            Path: /follow
            Method: post

  UnfollowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: UnfollowHandler.handler
      Events:
        UnfollowApi:
          Type: Api
          Properties:
            Path: /unfollow
            Method: post

  PostStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: PostStatusHandler.handler
      Events:
        PostStatusApi:
          Type: Api
          Properties:
            Path: /status/post
            Method: post

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: LogoutHandler.handler
      Events:
        LogoutApi:
          Type: Api
          Properties:
            Path: /logout
            Method: post
