AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Tweeter Milestone 4

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 256
    Tracing: Active
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"
      
Resources:
  GetFollowerCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetFollowerCountHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        GetFollowerCountApi:
          Type: Api
          Properties:
            Path: /follower/count
            Method: post

  GetFolloweeCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetFolloweeCountHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        GetFolloweeCountApi:
          Type: Api
          Properties:
            Path: /followee/count
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: LoginHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /login
            Method: post

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: RegisterHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        RegisterApi:
          Type: Api
          Properties:
            Path: /register
            Method: post

  FollowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: FollowHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        FollowApi:
          Type: Api
          Properties:
            Path: /follow
            Method: post

  UnfollowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: UnfollowHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        UnfollowApi:
          Type: Api
          Properties:
            Path: /unfollow
            Method: post

  PostStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: PostStatusHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        PostStatusApi:
          Type: Api
          Properties:
            Path: /status/post
            Method: post

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: LogoutHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        LogoutApi:
          Type: Api
          Properties:
            Path: /logout
            Method: post

  IsFollowerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: IsFollowerHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        IsFollowerApi:
          Type: Api
          Properties:
            Path: /follower/isFollower
            Method: post

  GetFollowersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetFollowersHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        GetFollowersApi:
          Type: Api
          Properties:
            Path: /follower/list
            Method: post

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetUserHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        GetUserApi:
          Type: Api
          Properties:
            Path: /user/get
            Method: post

  GetFolloweesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetFolloweesHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        GetFolloweesApi:
          Type: Api
          Properties:
            Path: /followee/list
            Method: post

  GetFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetFeedHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        GetFeedApi:
          Type: Api
          Properties:
            Path: /status/feed
            Method: post

  GetStoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: GetStoryHandler.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        GetStoryApi:
          Type: Api
          Properties:
            Path: /status/story
            Method: post
